export const fontRegistry = [
  {
    fontFamily: 'Aldedesign-WisdomMerry',
    displayName: 'Aldedesign-WisdomMerry',
    script: true,
    size: 2,
    favorite: false,
  },
  {
    fontFamily: 'Apricots-Regular',
    displayName: 'Apricots',
    script: true,
    size: 2,
    favorite: false,
  },
  {
    fontFamily: 'Awanstudio-Aubrielle-Regular',
    displayName: 'Awanstudio-Aubrielle',
    script: true,
    size: 3.5,
    favorite: false,
  },
  {
    fontFamily: 'Bralyn',
    displayName: 'Bralyn',
    script: true,
    size: 3.5,
    favorite: false,
  },
  {
    fontFamily: 'BrittanySignature',
    displayName: 'BrittanySignature',
    script: true,
    size: 2,
    favorite: false,
  },
  {
    fontFamily: 'CultivatedMind-GardenGrownBCaps',
    displayName: 'CultivatedMind-GardenGrown',
    script: false,
    size: 2,
    favorite: false,
  },
  {
    fontFamily: 'Datalegreya-Dot',
    displayName: 'Datalegreya-Dot',
    script: false,
    size: 2,
    favorite: false,
  },
  {
    fontFamily: 'Dmitrii Chirkov-Joshico-Regular',
    displayName: 'Dmitrii Chirkov-Joshico',
    script: true,
    size: 2,
    favorite: false,
  },
  {
    fontFamily: 'Fikryal-HelloSnowflake',
    displayName: 'Fikryal-HelloSnowflake',
    script: true,
    size: 3,
    favorite: false,
  },
  {
    fontFamily: 'Gistesy',
    displayName: 'Gistesy',
    script: true,
    size: 3,
    favorite: false,
  },
  {
    fontFamily: 'hellohoney',
    displayName: 'hellohoney',
    script: true,
    size: 2,
    favorite: false,
  },
  {
    fontFamily: 'JeffLevine-InlineRetroJNL',
    displayName: 'JeffLevine-InlineRetroJNL',
    script: false,
    size: 2,
    favorite: false,
  },
  {
    fontFamily: 'Khurasan-Sheenaz',
    displayName: 'Khurasan-Sheenaz',
    script: true,
    size: 2,
    favorite: false,
  },
  {
    fontFamily: 'KimberlyGeswein-KGRiseUP',
    displayName: 'KimberlyGeswein-KGRiseUP',
    script: false,
    size: 2,
    favorite: false,
  },
  {
    fontFamily: 'LoveloBlack',
    displayName: 'LoveloBlack',
    script: false,
    size: 2,
    favorite: false,
  },
  {
    fontFamily: 'MadinaClean',
    displayName: 'MadinaClean',
    script: true,
    size: 2,
    favorite: false,
  },
  {
    fontFamily: 'MadinaCleanOrnaments',
    displayName: 'MadinaCleanOrnaments',
    script: true,
    size: 2,
    favorite: false,
  },
  {
    fontFamily: 'MegaType-KameliaScript-Regular',
    displayName: 'MegaType-KameliaScript-Regular',
    script: true,
    size: 2,
    favorite: false,
  },
  {
    fontFamily: 'MegaType-YasmineGardner',
    displayName: 'MegaType-YasmineGardner',
    script: true,
    size: 2,
    favorite: false,
  },
  {
    fontFamily: 'Pompiere-Regular',
    displayName: 'Pompiere',
    script: false,
    size: 2,
    favorite: false,
  },
  {
    fontFamily: 'Putracetol-CavilayScript',
    displayName: 'Putracetol-Cavilay',
    script: true,
    size: 2,
    favorite: false,
  },
  {
    fontFamily: 'Raleway-Medium',
    displayName: 'Raleway',
    script: false,
    size: 2,
    favorite: false,
  },
  {
    fontFamily: 'Samtype-HebrewKarina-Regular',
    displayName: 'Samtype-HebrewKarina',
    script: false,
    size: 2,
    favorite: false,
  },
  {
    fontFamily: 'SansAndSons-MonthoersSignature',
    displayName: 'SansAndSons-MonthoersSignature',
    script: true,
    size: 2,
    favorite: false,
  },
  {
    fontFamily: 'SoftMaker-TypewriterSerial',
    displayName: 'SoftMaker-TypewriterSerial',
    script: false,
    size: 2,
    favorite: false,
  },
  {
    fontFamily: 'SophiaRonald',
    displayName: 'SophiaRonald',
    script: true,
    size: 5,
    favorite: false,
  },
  {
    fontFamily: 'Typesketchbook-BetmRounded-ExtraLight',
    displayName: 'Typesketchbook-BetmRounded',
    script: false,
    size: 2,
    favorite: false,
  },
  {
    fontFamily: 'ZaneStudio-HelloSunriseScript',
    displayName: 'ZaneStudio-HelloSunrise',
    script: true,
    size: 3,
    favorite: false,
  },
  {
    fontFamily: 'Alegreya-Regular',
    displayName: 'Alegreya',
    script: false,
    size: 2,
    favorite: false,
  },
  {
    fontFamily: 'BebasNeue-Regular',
    displayName: 'BebasNeue',
    script: false,
    size: 2,
    favorite: false,
  },
  {
    fontFamily: 'Fontforecast-SaltAndSpicesMonoBold',
    displayName: 'Fontforecast-SaltAndSpices',
    script: true,
    size: 2,
    favorite: false,
  },
  {
    fontFamily: 'Hanoded-LemonYellowSunExtraBoldRegular',
    displayName: 'Hanoded-LemonYellowSun',
    script: false,
    size: 2,
    favorite: false,
  },
  {
    fontFamily: 'Lemonthe-CaltonEleganceScript',
    displayName: 'Lemonthe-CaltonEleganceScript',
    script: true,
    size: 2,
    favorite: false,
  },
  {
    fontFamily: 'LibreBaskerville-Regular',
    displayName: 'LibreBaskerville',
    script: false,
    size: 2,
    favorite: false,
  },
  {
    fontFamily: 'MalisiaScript',
    displayName: 'MalisiaScript',
    script: true,
    size: 2,
    favorite: false,
  }
];

export const getScriptFonts = fontRegistry
  .filter(({script}) => script);

export const getBlockFonts = fontRegistry
  .filter(({script}) => !script);
