export const fontRegistry = [
  {
    fontFamily: 'Aldedesign-WisdomMerry',
    displayName: 'elizabeth',
    script: true,
    size: 3.5,
    favorite: false,
  },
  {
    fontFamily: 'Apricots-Regular',
    displayName: 'Charlotte',
    script: true,
    size: 3.5,
    favorite: false,
  },
  {
    fontFamily: 'Awanstudio-Aubrielle-Regular',
    displayName: 'Aubree',
    script: true,
    size: 4.5,
    favorite: false,
  },
  {
    fontFamily: 'Bralyn',
    displayName: 'Jane',
    script: true,
    size: 4.5,
    favorite: false,
  },
  {
    fontFamily: 'BrittanySignature',
    displayName: 'Brittany',
    script: true,
    size: 3.5,
    favorite: false,
  },
  {
    fontFamily: 'CultivatedMind-GardenGrownBCaps',
    displayName: 'EMMETT',
    script: false,
    size: 3.5,
    favorite: false,
  },
  {
    fontFamily: 'Datalegreya-Dot',
    displayName: 'WESTON',
    script: false,
    size: 3.5,
    favorite: false,
  },
  {
    fontFamily: 'Dmitrii Chirkov-Joshico-Regular',
    displayName: 'Mandy',
    script: true,
    size: 3.5,
    favorite: false,
    styles: {
      fontVariantLigatures: 'none'
    }
  },
  {
    fontFamily: 'Fikryal-HelloSnowflake',
    displayName: 'Jasmine',
    script: true,
    size: 4,
    favorite: false,
  },
  {
    fontFamily: 'Gistesy',
    displayName: 'Gabby',
    script: true,
    size: 4,
    favorite: false,
  },
  {
    fontFamily: 'hellohoney',
    displayName: 'Haley',
    script: true,
    size: 4.5,
    favorite: false,
  },
  {
    fontFamily: 'JeffLevine-InlineRetroJNL',
    displayName: 'OLIVER',
    script: false,
    size: 3.5,
    favorite: false,
  },
  {
    fontFamily: 'Khurasan-Sheenaz',
    displayName: 'Heather',
    script: true,
    size: 4.5,
    favorite: false,
  },
  {
    fontFamily: 'KimberlyGeswein-KGRiseUP',
    displayName: 'Robert',
    script: false,
    size: 3.5,
    favorite: false,
  },
  {
    fontFamily: 'LoveloBlack',
    displayName: 'BRAXTON',
    script: false,
    size: 3.5,
    favorite: false,
  },
  {
    fontFamily: 'MadinaClean',
    displayName: 'Sally',
    script: true,
    size: 3.5,
    favorite: false,
  },
  {
    fontFamily: 'MegaType-KameliaScript-Regular',
    displayName: 'Danielle',
    script: true,
    size: 3.5,
    favorite: false,
  },
  {
    fontFamily: 'MegaType-YasmineGardner',
    displayName: 'Rosalie',
    script: true,
    size: 3.5,
    favorite: false,
  },
  {
    fontFamily: 'Pompiere-Regular',
    displayName: 'Alexander',
    script: false,
    size: 3.5,
    favorite: false,
  },
  {
    fontFamily: 'Putracetol-CavilayScript',
    displayName: 'Scarlett',
    script: true,
    size: 3.5,
    favorite: false,
  },
  {
    fontFamily: 'Raleway-Medium',
    displayName: 'Benjamin',
    script: false,
    size: 3.5,
    favorite: false,
  },
  {
    fontFamily: 'Samtype-HebrewKarina-Regular',
    displayName: 'Jonathan',
    script: false,
    size: 3.5,
    favorite: false,
  },
  {
    fontFamily: 'SoftMaker-TypewriterSerial',
    displayName: 'hunter',
    script: false,
    size: 3.5,
    favorite: false,
  },
  {
    fontFamily: 'SophiaRonald',
    displayName: 'Sofia',
    script: true,
    size: 7,
    favorite: false,
  },
  {
    fontFamily: 'Typesketchbook-BetmRounded-ExtraLight',
    displayName: 'Carter',
    script: false,
    size: 3.5,
    favorite: false,
  },
  {
    fontFamily: 'ZaneStudio-HelloSunriseScript',
    displayName: 'Abigail',
    script: true,
    size: 5,
    favorite: false,
  },
  {
    fontFamily: 'Alegreya-Regular',
    displayName: 'Nathan',
    script: false,
    size: 3.5,
    favorite: false,
  },
  {
    fontFamily: 'BebasNeue-Regular',
    displayName: 'PATRICK',
    script: false,
    size: 3.5,
    favorite: false,
  },
  {
    fontFamily: 'Fontforecast-SaltAndSpicesMonoBold',
    displayName: 'Emmie',
    script: true,
    size: 3.5,
    favorite: false,
  },
  {
    fontFamily: 'Hanoded-LemonYellowSunExtraBoldRegular',
    displayName: 'JOSHUA',
    script: false,
    size: 3.5,
    favorite: false,
  },
  {
    fontFamily: 'Lemonthe-CaltonEleganceScript',
    displayName: 'Callie',
    script: true,
    size: 4.5,
    favorite: false,
  },
  {
    fontFamily: 'LibreBaskerville-Regular',
    displayName: 'Damien',
    script: false,
    size: 3.5,
    favorite: false,
  },
  {
    fontFamily: 'MalisiaScript',
    displayName: 'Celine',
    script: true,
    size: 3.5,
    favorite: false,
  },
  {
    fontFamily: 'Blushed',
    displayName: 'Paisley',
    script: true,
    size: 3.5,
    favorite: false,
  },
  {
    fontFamily: 'Foxtrot',
    displayName: 'JACKSON',
    script: false,
    size: 3.5,
    favorite: false,
  },
  {
    fontFamily: 'Gingerly',
    displayName: 'CHARLES',
    script: false,
    size: 3.5,
    favorite: false,
  },
  {
    fontFamily: 'HoneyButter',
    displayName: 'GRAYSON',
    script: false,
    size: 3.5,
    favorite: false,
  },
  ////////////////////////////////
  // New fonts - block
  {
    fontFamily: 'Backroads',
    displayName: 'Brodie',
    script: false,
    size: 3.5,
    favorite: false,
  },
  {
    fontFamily: 'BonVivantSerifBold',
    displayName: 'Bonnie',
    script: false,
    size: 3.5,
    favorite: false,
  },
  {
    fontFamily: 'ColdBrew',
    displayName: 'Bev',
    script: false,
    size: 3.5,
    favorite: false,
  },
  {
    fontFamily: 'Elementary',
    displayName: 'Boston',
    script: false,
    size: 3.5,
    favorite: false,
  },
  {
    fontFamily: 'GeorgiaPeach',
    displayName: 'Georgia',
    script: false,
    size: 3.5,
    favorite: false,
  },
  {
    fontFamily: 'Imaginary',
    displayName: 'Imogen',
    script: false,
    size: 3.5,
    favorite: false,
  },
  {
    fontFamily: 'MagicDust',
    displayName: 'Maggie',
    script: false,
    size: 3.5,
    favorite: false,
  },
  {
    fontFamily: 'Roselyn2',
    displayName: 'Robin',
    script: false,
    size: 3.5,
    favorite: false,
  },
  {
    fontFamily: 'SafeHolidayFamily',
    displayName: 'Poppy',
    script: false,
    size: 3.5,
    favorite: false,
  },
  {
    fontFamily: 'Sparkle',
    displayName: 'Sparkle',
    script: false,
    size: 3.5,
    favorite: false,
  },
  {
    fontFamily: 'WildMango',
    displayName: 'Indie',
    script: false,
    size: 3.5,
    favorite: false,
  },
  {
    fontFamily: 'Imaginary',
    displayName: 'Imogen',
    script: false,
    size: 3.5,
    favorite: false,
  },
  ////////////////////////////////
  // New fonts - script
  {
    fontFamily: 'Imaginary',
    displayName: 'Imogen',
    script: true,
    size: 3.5,
    favorite: false,
  },
];

export const getScriptFonts = fontRegistry
  .filter(({script}) => script);

export const getBlockFonts = fontRegistry
  .filter(({script}) => !script);
